[build]
  base = "."
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://fonts.googleapis.com https://esm.sh; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com https://fonts.cdnfonts.com; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com https://fonts.cdnfonts.com; img-src 'self' data: https: https://*.googleapis.com https://*.googleusercontent.com https://wehcgfyykmqhcuzjykio.supabase.co; media-src 'self' blob: data:; connect-src 'self' https://api.openai.com https://generativelanguage.googleapis.com https://*.googleapis.com https://*.googleusercontent.com https://wehcgfyykmqhcuzjykio.supabase.co https://esm.sh https://cdnjs.cloudflare.com https://fonts.googleapis.com https://fonts.gstatic.com https://fonts.cdnfonts.com; frame-src 'self'"